pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-repo/student-management.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Deploy to AWS') {
            steps {
                sshagent(['aws-ec2-credentials']) {
                    sh '''
                        scp target/student-management-0.0.1-SNAPSHOT.jar ec2-user@<AWS_EC2_IP>:/home/ec2-user/
                        ssh ec2-user@<AWS_EC2_IP> 'java -jar /home/ec2-user/student-management-0.0.1-SNAPSHOT.jar &'
                    '''
                }
            }
        }
    }
}